import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "../provider";
import Structure from "../components/Structure";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apna Pay",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
        <body suppressHydrationWarning={true} className={"h-full"}>
          <Structure>{children}</Structure>
        </body>
      </Providers>
    </html>
  );
}
